Theoretical Questions:

Numpy Assignment

1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it 
enhance Python's capabilities for numerical operations?

In [104]:
#NumPy, short for Numerical Python, is a fundamental library in Python for scientific computing and data analysis. Its main purpose is to provide support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these data structures. Here are some key purposes and advantages of NumPy:

# Purpose of NumPy
#1. **Array Operations**: NumPy introduces the `ndarray` object, which is a fast and flexible container for large data sets in Python. This array is more efficient than Python's built-in lists for numerical operations.
#2. **Mathematical Functions**: It provides a wide range of mathematical functions to perform operations on arrays, including element-wise operations, linear algebra, statistical functions, and more.
#3. **Interoperability**: NumPy is designed to integrate seamlessly with other libraries and tools in the scientific computing ecosystem, such as SciPy, Matplotlib, and Pandas.

# Advantages of NumPy
#1. **Performance**: NumPy arrays are implemented in C, allowing for faster computations compared to standard Python lists. Operations on NumPy arrays are typically vectorized, meaning they are executed in compiled code, leading to significant performance improvements.
#2. **Memory Efficiency**: NumPy arrays consume less memory compared to Python lists because they store data in a contiguous block of memory and support a variety of data types.
#3. **Ease of Use**: The library provides a high-level interface that simplifies complex mathematical operations. Users can perform operations on entire arrays without writing loops, which leads to cleaner and more readable code.
#4. **Broad Functionality**: NumPy supports a comprehensive set of functions for mathematical operations, random number generation, Fourier transforms, and linear algebra, making it a versatile tool for a wide range of scientific applications.
#5. **Broadcasting**: NumPy's broadcasting feature allows for arithmetic operations between arrays of different shapes, making it easy to perform operations without needing to manually reshape arrays.
#6. **Integration with Other Libraries**: NumPy serves as the foundation for many other scientific computing libraries in Python. For instance, Pandas uses NumPy for its data structures, and many machine learning libraries (like TensorFlow and scikit-learn) rely on NumPy for efficient computation.
# Enhancing Python's Capabilities
#Overall, NumPy significantly enhances Python's capabilities for numerical operations by providing efficient data structures and functions that allow for fast and easy manipulation of large datasets. This makes Python a powerful tool for scientists, engineers, and data analysts who require robust numerical analysis and data processing capabilities.

2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the 
other?

In [106]:
#In NumPy, both `np.mean()` and `np.average()` are used to compute the average of array elements, but they have some differences in functionality and usage. Here’s a comparison:

# `np.mean()`
#**Functionality**: Computes the arithmetic mean of the elements along the specified axis. It simply sums up all the elements and divides by the count of elements.
#**Syntax**: `np.mean(a, axis=None, dtype=None, out=None, keepdims=False)`
#**Use Case**: Use `np.mean()` when you want to calculate the mean value of an array or along a specific axis without any additional weighting. It's straightforward and efficient for standard mean calculations.

# `np.average()`
#**Functionality**: Computes the weighted average of the elements. You can specify weights for the elements, allowing for more flexibility in how the average is computed.
#**Syntax**: `np.average(a, axis=None, weights=None, returned=False)`
#**Use Case**: Use `np.average()` when you need to compute an average where certain values contribute more than others. This is particularly useful in cases where you have different levels of importance or frequency for the elements in your dataset.

# Key Differences
#1. **Weights**: 
   #`np.mean()` does not allow for weights; all elements are treated equally.
   #`np.average()` allows for an optional `weights` parameter, enabling you to specify how much influence each element has on the average.

#2. **Return Value**: 
   #Both functions return the computed average, but `np.average()` can return a tuple if `returned=True`, providing both the average and the sum of the weights.

#When to Use Which
#**Use `np.mean()`** when:
  # You need a quick and standard mean calculation.
  # All data points are equally important.

#**Use `np.average()`** when:
  # You need to consider weights for the data points.
  # You're dealing with datasets where certain values should have more influence on the average (e.g., weighted scores).

3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D 
arrays

In [108]:
#Reversing a NumPy array can be done easily using slicing or specific functions. 
#Here’s how you can reverse arrays along different axes, with examples for both 1D and 2D arrays.

# Reversing a 1D Array
#For a one-dimensional array, you can reverse the array using slicing.

# Example:

import numpy as np

array_1d = np.array([1, 2, 3, 4, 5])
reversed_1d = array_1d[::-1]


# Reversing a 2D Array
#For a two-dimensional array, you can reverse along specific axes using slicing.

# Example:

array_2d = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])
reversed_2d = array_2d[::-1]

In [109]:
print(reversed_1d)

[5 4 3 2 1]


In [110]:
print(reversed_2d)

[[7 8 9]
 [4 5 6]
 [1 2 3]]


4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types 
in memory management and performance.

In [112]:
#In NumPy, you can determine the data type of elements in an array using the .dtype attribute of the array. 
#Importance of Data Types
#Memory Management:
#Each data type in NumPy corresponds to a specific size in memory. For example, an int32 occupies 4 bytes, while an int64 occupies 8 bytes. Using the appropriate data type can significantly reduce memory usage, especially when dealing with large datasets.
#Choosing the right data type ensures that you don’t waste memory; for instance, if you only need values between 0 and 255, using np.uint8 (1 byte) is more efficient than using np.int64 (8 bytes).

#Performance:
#The performance of numerical computations can be impacted by data types. Operations on smaller data types (like float32 vs. float64) can be faster due to reduced computational overhead. However, the precision of calculations may also vary, so it's essential to balance speed and accuracy.
#NumPy uses optimized C libraries for operations on arrays. The choice of data type can influence how effectively these optimizations apply.

#Type Safety:
#Data types provide a level of type safety. For example, if you expect an array to contain integers, using a float or complex number can lead to unexpected behavior or errors in calculations.
#Compatibility:

#When performing operations between arrays, NumPy automatically handles type promotion (e.g., adding an integer array to a float array results in a float array). Understanding the data types involved is crucial for predicting the outcome of such operations

5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?


In [114]:
#In NumPy, **ndarrays** (n-dimensional arrays) are the core data structure used to store and manipulate numerical data. They are similar to Python lists but have several key features that make them more suitable for scientific computing and data analysis.

# Key Features of ndarrays

#1. **Homogeneous Data Type**: 
#  - All elements in a NumPy ndarray must be of the same data type (e.g., all integers, all floats). This is different from Python lists, which can hold mixed data types.

#2. **Multidimensional**: 
 #  - ndarrays can be one-dimensional (like vectors), two-dimensional (like matrices), or multi-dimensional (tensors). This flexibility allows for complex data representations.

#3. **Contiguous Memory**:
 #  - ndarrays are stored in a contiguous block of memory, which enhances performance for numerical computations compared to Python lists that are composed of pointers to objects scattered in memory.

#4. **Vectorized Operations**:
 #  - NumPy allows for element-wise operations on arrays without the need for explicit loops. This is possible due to its ability to perform operations in a vectorized manner, which leads to more concise code and faster execution.

#5. **Broadcasting**:
 #  - ndarrays support broadcasting, which allows for arithmetic operations between arrays of different shapes. This feature simplifies code and reduces the need for manual alignment of shapes.

#6. **Rich Functionality**:
 #  - NumPy provides a vast library of mathematical functions, linear algebra operations, statistical functions, and more, which are optimized for performance and can be applied directly to ndarrays.

#7. **Shape and Size**:
 #  - ndarrays have a shape attribute that provides the dimensions of the array (e.g., shape `(3, 4)` for a 2D array with 3 rows and 4 columns) and a size attribute that gives the total number of elements.

# Differences from Standard Python Lists

#1. **Type Consistency**:
 #  - **ndarrays**: Must be homogeneous (same data type).
  # - **Python lists**: Can be heterogeneous (mixed data types).

#2. **Performance**:
 #  - **ndarrays**: Optimized for performance with faster array operations due to contiguous memory storage and low-level optimizations.
  # - **Python lists**: Slower for numerical computations as they are not optimized for such tasks.

#3. **Functionality**:
 #  - **ndarrays**: Provide a wide range of built-in functions for mathematical operations and array manipulation.
  # - **Python lists**: Require explicit loops and list comprehensions for numerical operations.

#4. **Memory Efficiency**:
 #  - **ndarrays**: More memory-efficient for large datasets because of their fixed data type and contiguous memory allocation.
  # - **Python lists**: Can consume more memory due to overhead associated with storing references to objects.

#5. **Data Manipulation**:
 #  - **ndarrays**: Support advanced features like slicing, reshaping, and broadcasting.
  # - **Python lists**: Have basic indexing and slicing capabilities, but less efficient for reshaping and multi-dimensional manipulations.

6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.

In [123]:
#NumPy arrays provide several performance benefits over Python lists, particularly for large-scale numerical operations. Here’s a detailed analysis of these advantages:

# 1. **Memory Efficiency**
#- **Contiguous Memory Allocation**: NumPy arrays are stored in contiguous blocks of memory. This means that all elements are stored next to each other, reducing overhead and improving cache performance. In contrast, Python lists are composed of pointers to objects scattered throughout memory, which can lead to higher memory consumption and fragmentation.
#- **Fixed Data Type**: NumPy arrays are homogeneous, meaning all elements are of the same data type. This allows NumPy to use a more compact representation (e.g., `int32`, `float64`), whereas Python lists can hold objects of different types, increasing memory usage.

# 2. **Speed of Operations**
#- **Vectorization**: NumPy allows for vectorized operations, meaning that arithmetic operations can be applied to entire arrays at once without the need for explicit loops. This is typically implemented in optimized C code, resulting in significant speed improvements. In contrast, operations on Python lists often require looping through each element, which is slower.

# 3. **Broadcasting**
#- **Ease of Use and Performance**: NumPy supports broadcasting, which allows for operations between arrays of different shapes without the need for manual replication of data. This reduces the need for additional memory allocation and can lead to performance gains during operations.

# 4. **Built-in Functions**
#- **Optimized Libraries**: NumPy comes with a wide array of built-in functions that are highly optimized for performance. These functions take advantage of low-level optimizations and parallelism, allowing for faster execution than equivalent Python code using loops.

# 5. **Reduced Overhead**
#- **Function Call Overhead**: When working with Python lists, each operation often involves additional overhead due to the dynamic nature of lists and the need for Python's object management. NumPy's fixed-type, homogeneous arrays reduce this overhead, leading to faster execution times.

# 6. **Multi-threading and Parallelization**
#- **Integration with Libraries**: NumPy can leverage optimized libraries such as BLAS (Basic Linear Algebra Subprograms) and LAPACK (Linear Algebra Package) that support multi-threading and vectorization. This can significantly speed up operations, especially for large datasets.


7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and 
output.

In [126]:
#In NumPy, `vstack()` and `hstack()` are functions used to stack arrays vertically and horizontally, respectively. They allow you to combine multiple arrays along a specified axis, which is useful for constructing larger arrays from smaller ones.

### `vstack()`
#- **Purpose**: Stacks arrays in sequence vertically (row-wise). This means that the input arrays are stacked on top of each other.
#- **Axis**: The stacking occurs along the first axis (axis 0).

# `hstack()`
#- **Purpose**: Stacks arrays in sequence horizontally (column-wise). This means that the input arrays are placed side by side.
#- **Axis**: The stacking occurs along the second axis (axis 1).

In [128]:
import numpy as np

# `vstack()`
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

result_vstack = np.vstack((array1, array2))

print("Result of vstack:")
print(result_vstack)

Result of vstack:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [130]:
# `hstack()`
result_hstack = np.hstack((array1, array2))

print("Result of hstack:")
print(result_hstack)

Result of hstack:
[[1 2 5 6]
 [3 4 7 8]]


8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various 
array dimensions

In [133]:
#In NumPy, the `fliplr()` and `flipud()` methods are used to flip arrays along different axes. They are useful for reversing the order of elements along rows (left-right) or columns (up-down), depending on the direction of the flip.

# `fliplr()` – Flip Left-Right (Horizontally)
#- **Purpose**: The `fliplr()` method flips an array **left to right** along the second axis (axis 1), meaning the columns are reversed.
#- **Effect**: This method reverses the order of elements in each row (but does not change the rows themselves).


# `flipud()` – Flip Up-Down (Vertically)
#- **Purpose**: The `flipud()` method flips an array **up to down** along the first axis (axis 0), meaning the rows are reversed.
# **Effect**: This method reverses the order of rows but does not change the order of elements within each row.

#As shown, the `flipud()` method reverses the order of the rows, flipping the entire array vertically.

# Differences Between `fliplr()` and `flipud()`
#- **Axis of Operation**:
 # - **`fliplr()`** flips the array horizontally along axis 1 (reverses the columns).
  #- **`flipud()`** flips the array vertically along axis 0 (reverses the rows).
  
#- **Effect on Array Dimensions**:
 # - **1D arrays**: 
  #  - `fliplr()` and `flipud()` behave the same on 1D arrays since the only axis is axis 0, and flipping horizontally or vertically is equivalent.
  #- **2D arrays**:
   # - `fliplr()` flips the columns (left to right).
   # - `flipud()` flips the rows (top to bottom).
 # - **Higher-dimensional arrays**:
  #  - These functions will still operate only on the first or second axes, respectively. For arrays with more than 2 dimensions (e.g., 3D), `flipud()` affects the "rows" along axis 0, and `fliplr()` affects the "columns" along axis 1.

In [135]:
import numpy as np

array_2d = np.array([[1, 2, 3], 
                     [4, 5, 6], 
                     [7, 8, 9]])

flipped_lr = np.fliplr(array_2d)

print("Original array:")
print(array_2d)

print("Array after fliplr:")
print(flipped_lr)

Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Array after fliplr:
[[3 2 1]
 [6 5 4]
 [9 8 7]]


In [137]:
flipped_ud = np.flipud(array_2d)

print("Original array:")
print(array_2d)

print("\nArray after flipud:")
print(flipped_ud)

Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Array after flipud:
[[7 8 9]
 [4 5 6]
 [1 2 3]]


9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?


In [140]:
#The `array_split()` method in NumPy is used to divide an array into multiple sub-arrays. It is a flexible tool for splitting arrays, especially when you don’t know the exact number of elements or when the number of elements cannot be perfectly divided by the specified number of splits.

# Functionality of `array_split()`

#The `array_split()` function splits an array into multiple sub-arrays along a specified axis. This method is useful for dividing a large dataset into smaller chunks, and it works with both 1D and multi-dimensional arrays.

# Syntax:
#numpy.array_split(ary, indices_or_sections, axis=0)

#- `ary`: The array to be split.
#- `indices_or_sections`: Can be an integer or a list/array of indices.
#- If it's an integer, it specifies the number of equal-sized sub-arrays you want to split the array into.
# - If it's a list or array of indices, it defines the points at which to split the array.
#- `axis`: The axis along which to split (default is 0, which splits the array along rows for 2D arrays). 

# Handling Uneven Splits

#One of the key features of `array_split()` is how it handles **uneven splits**. When the total number of elements in the array cannot be evenly divided by the number of requested splits, `array_split()` automatically distributes the elements as evenly as possible, but some sub-arrays may contain more elements than others.

#For instance, if you try to split an array of size 10 into 3 parts, `array_split()` will return 3 sub-arrays where:
#- Two of the sub-arrays will have 3 elements.
#- One of the sub-arrays will have 4 elements.

10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array 
operations?

In [143]:
#In NumPy, **vectorization** and **broadcasting** are powerful concepts that greatly enhance the efficiency of array operations, making them faster and more memory-efficient compared to using traditional Python loops.

# 1. **Vectorization in NumPy**
#Vectorization refers to the process of writing operations that can be applied to entire arrays (or large portions of arrays) without the need for explicit loops. This is done by using NumPy's built-in functions and operations, which are implemented in optimized C code and internally make use of low-level hardware capabilities like SIMD (Single Instruction, Multiple Data) instructions.

# How Vectorization Works
#Instead of using Python loops to perform operations on each element of an array (which can be slow), vectorized operations apply the operation directly to the entire array or a part of it. This leads to a significant speedup.

#For example, if you want to add a constant value to every element in an array, you can use vectorized operations instead of looping through the array manually.

#NumPy allows you to perform the operation directly on the whole array in a single line, making the code cleaner and faster.

# Performance Benefits of Vectorization:
#- **Faster execution**: Operations are executed in optimized, low-level code (often written in C or Fortran), leveraging CPU optimizations.
#- **Concise code**: Without the need for explicit loops, code becomes shorter and easier to read.
#- **Parallelism**: Many vectorized operations can be parallelized across multiple processor cores, improving performance for large arrays.

# 2. **Broadcasting in NumPy**
#Broadcasting is a set of rules that allow NumPy to perform element-wise operations on arrays of different shapes, without the need for explicit replication of data. When performing operations between arrays of different shapes, broadcasting automatically "expands" the smaller array to match the shape of the larger array so that the operation can be applied element-wise.

# Broadcasting Rules:
#1. **The dimensions of the arrays must be compatible.**
 #  - If the arrays have different numbers of dimensions, the shape of the smaller array is padded with ones on the left until both shapes are of equal length.
#2. **Arrays are broadcast to the shape of the larger array**. The dimensions of the smaller array are stretched (repeated) to match the shape of the larger array, but this happens without copying the data. The array’s original data is still reused.



# Broadcasting Rules in Detail:
#1. **If the arrays have different numbers of dimensions,** NumPy adds 1s to the left of the smaller array’s shape until both shapes have the same length.
#2. **When the shapes are aligned,** the operation is done element-wise. If one of the dimensions is 1, it is broadcast across the larger dimension.
#3. **The operation can only proceed if dimensions are either equal or one of them is 1.** If none of these conditions is met, a `ValueError` is raised.

# Performance Benefits of Broadcasting:
#- **Memory Efficiency**: Broadcasting avoids the need for creating copies of arrays by repeating data. Instead, it uses the existing data efficiently.
#- **Speed**: Broadcasting allows NumPy to perform operations on arrays of different shapes in a single pass, avoiding the need for explicit loops or replication, which reduces computational overhead.
#- **Simplified Code**: Broadcasting reduces the need for manually reshaping or replicating arrays, making the code cleaner and easier to maintain.

# How Vectorization and Broadcasting Contribute to Efficient Array Operations

#1. **Vectorization**:
 #  - Reduces the need for Python-level for loops.
 # - Leverages fast, low-level implementations in C.
 #- Makes operations concise and readable, which improves development efficiency.
 #- Improves execution speed for numerical operations by taking advantage of CPU optimizations.

#2. **Broadcasting**:
 #  - Allows for operations on arrays with different shapes without explicit reshaping or replication.
 #  - Saves memory by not duplicating data and instead using existing memory efficiently.
 #  - Provides a flexible way to perform element-wise operations on arrays of varying shapes, making it easier to handle complex operations with less code.

Practical Questions:

1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [154]:
import numpy as np

array = np.random.randint(1, 101,(3, 3))
print("Original Array:")
print(array)

print("\nTransposed Array (interchanged rows and columns):")
print(transposed_array)


Original Array:
[[84  8 58]
 [28 25 99]
 [67 16 16]]

Transposed Array (interchanged rows and columns):
[[66 17 30]
 [ 2 88 34]
 [45 67 29]]


2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.


In [157]:
import numpy as np
array_1d = np.arange(1, 11)  # Generate array with values from 1 to 10

# Step 2: Reshape it into a 2x5 array
array_2x5 = array_1d.reshape(2, 5)

# Step 3: Reshape it into a 5x2 array
array_5x2 = array_1d.reshape(5, 2)

# Display the original and reshaped arrays
print("Original 1D Array:")
print(array_1d)

print("\nReshaped to 2x5 Array:")
print(array_2x5)

print("\nReshaped to 5x2 Array:")
print(array_5x2)


Original 1D Array:
[ 1  2  3  4  5  6  7  8  9 10]

Reshaped to 2x5 Array:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

Reshaped to 5x2 Array:
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.


In [162]:
import numpy as np

# Step 1: Create a 4x4 NumPy array with random float values between 0 and 1
array_4x4 = np.random.rand(4, 4)

# Step 2: Add a border of zeros around the 4x4 array to make it a 6x6 array
array_with_border = np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0)

# Display the original array and the array with the border
print("Original 4x4 Array:")
print(array_4x4)

print("\nArray with a border of zeros (6x6):")
print(array_with_border)


Original 4x4 Array:
[[0.62586316 0.12271509 0.77942598 0.07048149]
 [0.51849938 0.62557857 0.05084538 0.13594574]
 [0.4975425  0.73503075 0.23847852 0.67434034]
 [0.60205867 0.01610436 0.90491058 0.2415147 ]]

Array with a border of zeros (6x6):
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.62586316 0.12271509 0.77942598 0.07048149 0.        ]
 [0.         0.51849938 0.62557857 0.05084538 0.13594574 0.        ]
 [0.         0.4975425  0.73503075 0.23847852 0.67434034 0.        ]
 [0.         0.60205867 0.01610436 0.90491058 0.2415147  0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.


In [168]:
import numpy as np

# Create an array of integers from 10 to 60 with a step of 5
array = np.arange(10, 59, 5)

# Display the array
print(array)

[10 15 20 25 30 35 40 45 50 55]


5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations 
(uppercase, lowercase, title case, etc.) to each element

In [175]:
import numpy as np

# Create a NumPy array of strings
array = np.array(['python', 'numpy', 'pandas'])

# Apply different case transformations
upper_case = np.char.upper(array)       # Convert all strings to uppercase
lower_case = np.char.lower(array)       # Convert all strings to lowercase
title_case = np.char.title(array)       # Convert all strings to title case
capitalize_case = np.char.capitalize(array)  # Capitalize the first letter of each string

# Display the original and transformed arrays
print("Original Array:")
print(array)

print("\nUppercase:")
print(upper_case)

print("\nLowercase:")
print(lower_case)

print("\nTitle Case:")
print(title_case)

print("\nCapitalize Case:")
print(capitalize_case)


Original Array:
['python' 'numpy' 'pandas']

Uppercase:
['PYTHON' 'NUMPY' 'PANDAS']

Lowercase:
['python' 'numpy' 'pandas']

Title Case:
['Python' 'Numpy' 'Pandas']

Capitalize Case:
['Python' 'Numpy' 'Pandas']


6. Generate a NumPy array of words. Insert a space between each character of every word in the array.


In [178]:
import numpy as np

# Create a NumPy array of words
words_array = np.array(['python', 'numpy', 'pandas'])

# Insert a space between each character of every word
words_with_spaces = np.char.add(np.char.array(list(words_array)), ' ')

# Display the original and transformed arrays
print("Original Array:")
print(words_array)

print("\nArray with spaces between characters:")
print(words_with_spaces)

Original Array:
['python' 'numpy' 'pandas']

Array with spaces between characters:
['python ' 'numpy ' 'pandas ']


7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.


In [187]:
import numpy as np

# Create two 2D NumPy arrays
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[6, 5, 4], [3, 2, 1]])

# Perform element-wise addition
addition = array1 + array2

# Perform element-wise subtraction
subtraction = array1 - array2

# Perform element-wise multiplication
multiplication = array1 * array2

# Perform element-wise division
division = array1 / array2

# Display the results
print("Array 1:")
print(array1)

print("\nArray 2:")
print(array2)

print("\nElement-wise Addition:")
print(addition)

print("\nElement-wise Subtraction:")
print(subtraction)

print("\nElement-wise Multiplication:")
print(multiplication)

print("\nElement-wise Division:")
print(division)

Array 1:
[[1 2 3]
 [4 5 6]]

Array 2:
[[6 5 4]
 [3 2 1]]

Element-wise Addition:
[[7 7 7]
 [7 7 7]]

Element-wise Subtraction:
[[-5 -3 -1]
 [ 1  3  5]]

Element-wise Multiplication:
[[ 6 10 12]
 [12 10  6]]

Element-wise Division:
[[0.16666667 0.4        0.75      ]
 [1.33333333 2.5        6.        ]]


8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.


In [190]:
import numpy as np

# Step 1: Create a 5x5 identity matrix
identity_matrix = np.eye(5)

# Step 2: Extract the diagonal elements
diagonal_elements = identity_matrix.diagonal()

# Display the identity matrix and its diagonal elements
print("5x5 Identity Matrix:")
print(identity_matrix)

print("\nDiagonal Elements:")
print(diagonal_elements)

5x5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal Elements:
[1. 1. 1. 1. 1.]


9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in 
this array.

In [193]:
import numpy as np

# Step 1: Generate a NumPy array of 100 random integers between 0 and 1000
random_integers = np.random.randint(0, 1001, 100)

# Step 2: Define a function to check if a number is prime
def is_prime(num):
    if num < 2:
        return False
    for i in range(2, int(num ** 0.5) + 1):
        if num % i == 0:
            return False
    return True

# Step 3: Apply the is_prime function to each element in the array
prime_numbers = [num for num in random_integers if is_prime(num)]

# Step 4: Display the prime numbers
print("Random Integers:")
print(random_integers)

print("\nPrime Numbers in the Array:")
print(prime_numbers)

Random Integers:
[  4 409 197 833 141 961 440 345  38  22 509 131 827 190 275  73 547 909
 786 886 857 591  95 113 504 619 653 525 408 671 574 220  29 640  24  25
 607 572 352 591  88 663 919 307 735  88 273 704 823 888 587 985 703 373
 241 711 125   2 958 456 775 935 269 694  51 332 954 326  42 938 822 596
 909 170 376 521 283 599 873 776 455 771 100 985 218 672 791 391 256 522
 780 955 969  30 119 257 192 103 559 161]

Prime Numbers in the Array:
[409, 197, 509, 131, 827, 73, 547, 857, 113, 619, 653, 29, 607, 919, 307, 823, 587, 373, 241, 2, 269, 521, 283, 599, 257, 103]


10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly 
averages.

In [220]:
import numpy as np

daily_temperatures = np.random.randint(15, 36, size=28)

weekly_temperatures = daily_temperatures.reshape(4, 7)

weekly_averages = weekly_temperatures.mean(axis=1)

print("Daily Temperatures for the Month:")
print(daily_temperatures)

print("\nWeekly Temperatures (4 weeks x 7 days):")
print(weekly_temperatures)

print("\nWeekly Averages:")
print(weekly_averages)


Daily Temperatures for the Month:
[22 17 30 22 17 34 22 15 15 31 29 17 31 19 33 33 35 27 16 30 15 29 18 32
 28 15 33 18]

Weekly Temperatures (4 weeks x 7 days):
[[22 17 30 22 17 34 22]
 [15 15 31 29 17 31 19]
 [33 33 35 27 16 30 15]
 [29 18 32 28 15 33 18]]

Weekly Averages:
[23.42857143 22.42857143 27.         24.71428571]
